name: sync-main-gh-pages
on:
  push:
    branches:
      - main
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: gh-pages
            - name: Configure Git
              run: |
                    git config --global user.email github-actions@github.com
                    git config --global user.name github-actions
            - name: Sync
              run: |
                    git merge origin/main
            - name: Push
              run: |
                    git push origin gh-pages